// import localFont from "next/font/local";
// import "../../globals.css";
import Link from "next/link";
import Image from "next/image";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/app/components/home/navbar";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Navbar />
      {children}
      <ToastContainer />
    </>
  )
}
